name: bayesshore
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - seaborn
  - pandas
  - ipywidgets
  - jupyterlab
  - scikit-learn
  - conda-forge::numpyro
  - conda-forge::arviz
  - pip:
    - streamlit